### ISSUE TITLE
Genus-Species Definitions

### ISSUE THREAD

**Issue by johnbeve** [SydCo99/MIDO#1]
MIDO definitions should be rewritten to follow the genus-species format. From pg. 69 of "Building Ontologies with Basic Formal Ontology": 

"The recommended best practice for creating definitions...is to use the Aristotelian form:
        S = def. a G that Ds,
where “G” (for: genus) is the immediate parent term of “S” (for: species) in the ontology
for which the definition is being created. “D” stands for differentia, which is to say: “D”
tells us what it is about certain Gs in virtue of which they are Ss. Ideally, the terms used
in formulating the differentia D will themselves be terms taken from some ontology,
where they will themselves be defined."

**Comment by SydCo99** [comment]
Very true! I have updated all the terms I added to IDO to reflect this structure. Thank you for pointing that out.
