### ISSUE TITLE
Remove Unnecessary Ontology Information

### ISSUE THREAD

**Issue by johnbeve** [SydCo99/MIDO#2]
I recommend importing needed non-MIDO ontology resources rather than recreating them in the MIDO.xml. There is a lot of unnecessary non-MIDO information in the file.

**Comment by SydCo99** [comment]
Great point, when I started this I was working off a full import of IDO, which I shouldn't have done. I've removed a lot of terms already, and some instances, which is reflected in the most recent version of the repo. I anticipate deleting more terms to make the class hierarchy as easy to navigate as possible while still retaining necessary infectious disease terms. Feel free to LMK if you see things you think should be removed. Thanks!
