### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by johnbeve** [SydCo99/MIDO#3]
Update the readme to contain an explanation of and motivation for MIDO, as well as any associated collaborators, news, publications, etc. CIDO provides a good example of the sort of information you might want to include: https://github.com/infectious-disease-ontology-extensions/cido

**Comment by SydCo99** [comment]
thanks John! I've edited the readme to reflect some of the thought behind creating MIDO and the taxon strategy pulled from UNITE - I also edited the readme for clarity by adding headings
